// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pacagroup.Trade.Persistence.Contexts;

#nullable disable

namespace Pacagroup.Trade.Persistence.Migrations
{
    [DbContext(typeof(AplicationDbContext))]
    [Migration("20251031122414_AlterOrderSchemeFixed")]
    partial class AlterOrderSchemeFixed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Pacagroup.Trade.Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .HasPrecision(9)
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasDefaultValue("USD");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<decimal>("Price")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<int>("Quantity")
                        .HasPrecision(9)
                        .HasColumnType("int");

                    b.Property<int>("Side")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Text")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("TransactTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasMaxLength(1)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Orders", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2025, 10, 31, 7, 22, 0, 0, DateTimeKind.Local),
                            CreatedBy = "system",
                            Currency = "USD",
                            Price = 522.99m,
                            Quantity = 1000,
                            Side = 0,
                            Symbol = "META",
                            Text = "Initial order for META stocks",
                            TransactTime = new DateTime(2025, 10, 21, 12, 0, 0, 0, DateTimeKind.Utc),
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2025, 10, 31, 7, 22, 0, 0, DateTimeKind.Local),
                            CreatedBy = "system",
                            Currency = "USD",
                            Price = 145.50m,
                            Quantity = 50,
                            Side = 0,
                            Symbol = "AAPL",
                            Text = "Initial order for AAPL stocks",
                            TransactTime = new DateTime(2025, 10, 23, 12, 0, 0, 0, DateTimeKind.Utc),
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2025, 10, 31, 7, 22, 0, 0, DateTimeKind.Local),
                            CreatedBy = "system",
                            Currency = "USD",
                            Price = 0m,
                            Quantity = 30,
                            Side = 1,
                            Symbol = "TSLA",
                            Text = "Initial order for TSLA stocks",
                            TransactTime = new DateTime(2025, 10, 26, 12, 0, 0, 0, DateTimeKind.Utc),
                            Type = 1
                        },
                        new
                        {
                            Id = 4,
                            Created = new DateTime(2025, 10, 31, 7, 22, 0, 0, DateTimeKind.Local),
                            CreatedBy = "system",
                            Currency = "USD",
                            Price = 0m,
                            Quantity = 200,
                            Side = 0,
                            Symbol = "AMZN",
                            Text = "Initial order for AMZN stocks",
                            TransactTime = new DateTime(2025, 10, 28, 12, 0, 0, 0, DateTimeKind.Utc),
                            Type = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
